# Para gerar o site estático: mkdocs build
# Para rodar um servidor para testes: mkdocs serve

site_name: Helios - Sistema de votação eletrônica
site_description: 'Ajuda do sistema de votação eletrônica'
site_author: 'Ascema Nacional'
copyright: 'Creative Commons 2020 - Ascema Nacional'

nav:
    - Como votar: index.md

extra_css:
  - stylesheets/extra.css

theme:
  name: 'material'
